services:
  aiam:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    volumes:
      - ./data:/app/data
    environment:
      ENVIRONMENT: local
      DATA_DIR: /app/data
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./frontend
